import * as zod from "zod";

export const customersSchema = zod.object({
  recordid: zod.coerce.number().int().nonnegative(),
  code_client: zod.string().max(20, "CODE_CLIENT must be at most 20 characters long"),
  client: zod.string().max(100, "CLIENT must be at most 100 characters long"),
  activite: zod.string().optional(),
  code_postal: zod.string().max(10, "CODE_POSTAL must be at most 10 characters long"),
  adresse: zod.string().max(100, "ADRESSE must be at most 100 characters long"),
  commune: zod.string().max(50, "COMMUNE must be at most 50 characters long"),
  wilaya: zod.string().max(25, "WILAYA must be at most 25 characters long"),
  contact: zod.string().max(40, "CONTACT must be at most 40 characters long"),
  tel: zod.string().max(50, "TEL must be at most 50 characters long"),
  fax: zod.string().max(40, "FAX must be at most 40 characters long"),
  num_rc: zod.string().max(20, "NUM_RC must be at most 20 characters long"),
  num_if: zod.string().max(20, "NUM_IF must be at most 20 characters long"),
  num_is: zod.string().max(20, "NUM_IS must be at most 20 characters long"),
  num_art: zod.string().max(20, "NUM_ART must be at most 20 characters long"),
  nin: zod.string().max(50, "NIN must be at most 50 characters long"),
  compte: zod.string().max(40, "COMPTE must be at most 40 characters long"),
  rib: zod.string().max(40, "RIB must be at most 40 characters long"),
  email: zod.string().max(50, "EMAIL must be at most 50 characters long"),
  site_web: zod.string().max(50, "SITE_WEB must be at most 50 characters long"),
  solde_ini: zod.coerce.number().int().nonnegative(),
  achats: zod.coerce.number().int().nonnegative().default(0),
  verser: zod.coerce.number().int().nonnegative().default(0),
  credit_limit: zod.coerce.number().int().nonnegative(),
  notes: zod.string().max(255, "NOTES must be at most 255 characters long"),
  famille: zod.string().max(50, "FAMILLE must be at most 50 characters long").nullable().optional(),
  sous_famille: zod.string().max(50, "SOUS_FAMILLE must be at most 50 characters long").nullable().optional(),
  nbr_bon: zod.coerce.number().int().nonnegative(),
  solde: zod.coerce.number().int(),
  mode_tarif: zod.string().max(1, "MODE_TARIF must be at most 1 characters long"),
  type_fid: zod.string().max(10, "TYPE_FID must be at most 10 characters long").nullable().optional(),
  num_cf: zod.string().max(20, "NUM_CF must be at most 20 characters long"),
  allow_credit: zod.coerce.number().int().nonnegative(),
  date_passage: zod.coerce.date().optional(),
  vis_admin: zod.coerce.number().int().nonnegative(),
  code_frs: zod.string().max(20, "CODE_FRS must be at most 20 characters long").nullable().optional(),
  code_depot: zod.string().max(6, "CODE_DEPOT must be at most 6 characters long").nullable().optional(),
  latitude: zod.coerce.number().nonnegative(),
  longitude: zod.coerce.number().nonnegative(),
  code_vendeur: zod.string().max(20, "CODE_VENDEUR must be at most 20 characters long").nullable().optional(),
  sup: zod.coerce.number().int().nonnegative(),
  date_er_modification: zod.coerce.date().optional(),
  utilisateur: zod.string().max(25, "UTILISATEUR must be at most 25 characters long"),
  nom_ord: zod.string().max(25, "NOM_ORD must be at most 25 characters long"),
  jrnl: zod.coerce.number().int().nonnegative(),
});

export type CustomerT = zod.infer<typeof customersSchema>;
